const endpointName = [
  { en: "braised-dish", vi: "Món kho" },
  { en: "cake", vi: "Bánh" },
  { en: "candied-fruit", vi: "Mứt trái cây" },
  { en: "drinks", vi: "Đồ uống" },
  { en: "fried-dish", vi: "Món chiên" },
  { en: "general-recipe", vi: "Công thức chung" },
  { en: "grilled-dish", vi: "Món nướng" },
  { en: "hotpot", vi: "Lẩu" },
  { en: "ice-cream", vi: "Kem" },
  { en: "kimchi", vi: "Kim chi" },
  { en: "meat-patty", vi: "Chả thịt" },
  { en: "nutritious-dish", vi: "Món bổ dưỡng" },
  { en: "pho", vi: "Phở" },
  { en: "pork-head-cheese", vi: "Giò thủ" },
  { en: "porridge", vi: "Cháo" },
  { en: "rice-dish", vi: "Cơm" },
  { en: "rice-noodle-dish", vi: "Bún" },
  { en: "salad-food", vi: "Gỏi" },
  { en: "salad", vi: "Salad" },
  { en: "soup", vi: "Súp" },
  { en: "specialties", vi: "Đặc sản" },
  { en: "spring-roll", vi: "Chả giò" },
  { en: "steamed-dish", vi: "Món hấp" },
  { en: "stew", vi: "Món hầm" },
  { en: "sticky-rice", vi: "Xôi" },
  { en: "stir-fried-dish", vi: "Món xào" },
  { en: "street-food", vi: "Món ăn đường phố" },
  { en: "sweet-and-sour-dish", vi: "Món chua ngọt" },
  { en: "sweet-soup", vi: "Chè" },
  { en: "thick-soup", vi: "Súp đặc" },
];

export default endpointName;
